### ISSUE TITLE
[Plugin] TypeTransformers for Numpy array, PyTorch and TensorFlow tensors

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#2544]
Since a majority of Flyte users work on ML, it'd be helpful to have Numpy arrays, PyTorch and Tensorflow tensors as Flyte types.

Related Slack conversation: 

> I am looking for a way to pass Numpy Arrays (ndarray) and PyTorch/Tensorflow Tensors as Flyte Task input/output. I haven’t come across any example yet. I’m aware of the native support for Dataframes. It seems inefficient to convert ndarray/Tensors back and forth using Dataframes.
> How are folks handling this?

https://flyte-org.slack.com/archives/CNMKCU6FR/p1653071185574619

### TODO

- [x] Numpy https://github.com/flyteorg/flytekit/pull/1027
- [x] PyTorch https://github.com/flyteorg/flytekit/pull/1032
- [ ] TensorFlow
    - [x] https://github.com/flyteorg/flyte/issues/2569
    - [x] https://github.com/flyteorg/flyte/issues/2570
    - [x] https://github.com/flyteorg/flyte/issues/2571

**Comment by badarahmed** [comment]
Thanks for opening the issue!

**Comment by sbrunk** [comment]
Numpy has a relatively stable representation for serialization on disk: https://github.com/numpy/numpy/blob/main/doc/neps/nep-0001-npy-format.rst

**Comment by samhita-alla** [comment]
> Numpy has a relatively stable representation for serialization on disk: https://github.com/numpy/numpy/blob/main/doc/neps/nep-0001-npy-format.rst

Looks promising! But I think we could use StructuredDataset to store the Numpy array as a parquet file. 
Numpy -> Pyarrow -> Parquet.

**Comment by cosmicBboy** [comment]
fixed by #1032
