### ISSUE TITLE
[Core feature] Flyte Agent Ecosystem

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#3936]
### Motivation: Why do you think this is important?

Create this issue to track all the PRs and issues related to the Flyte agent.

### Goal: What should the final outcome look like, ideally?

More agents, more reliable, easy to use and deploy.

### Describe alternatives you've considered 

NA

###  Propose: Link/Inline OR Additional context 

Todo:
- [x] [Databricks Agent](https://github.com/flyteorg/flytekit/pull/1797)
- [x] [Snowflake Agent](https://github.com/flyteorg/flytekit/pull/1799)
- [x] [Memverge Agent](https://github.com/flyteorg/flytekit/pull/1821)
- [x] [File sensor](https://github.com/flyteorg/flytekit/pull/1790)
- [ ] Sagemaker Agent
- [x] ChatGPT Agent
- [ ] LainChain Agent (TBD)

PRs:
- https://github.com/flyteorg/flyte/pull/3935
- https://github.com/flyteorg/flytekit/pull/1790
- https://github.com/flyteorg/flyteplugins/pull/384
- https://github.com/flyteorg/flytekit/pull/1781
- https://github.com/flyteorg/flytekit/pull/1778
- https://github.com/flyteorg/flytekit/pull/1782
- https://github.com/flyteorg/flytekit/pull/1773
- https://github.com/flyteorg/flytekit/pull/1725
- https://github.com/flyteorg/flytekit/pull/1712
- https://github.com/flyteorg/flyte/pull/3558
- https://github.com/flyteorg/flyteplugins/pull/381
- https://github.com/flyteorg/flyteplugins/pull/368
- https://github.com/flyteorg/flyteplugins/pull/353
- https://github.com/flyteorg/flyteplugins/pull/330
- https://github.com/flyteorg/flytepropeller/pull/564
- https://github.com/flyteorg/flyte/pull/3788
- https://github.com/flyteorg/flyte/pull/3454
- https://github.com/flyteorg/flyte/pull/3779
- https://github.com/flyteorg/flytesnacks/pull/971
- https://github.com/flyteorg/flytekit/pull/1815
- https://github.com/flyteorg/flyteplugins/pull/392
- https://github.com/flyteorg/flyteplugins/pull/398
- https://github.com/flyteorg/flyteplugins/pull/391
- https://github.com/flyteorg/flyteplugins/pull/402
- https://github.com/flyteorg/flytestdlib/pull/164
- https://github.com/flyteorg/flytekit/pull/1835
- https://github.com/flyteorg/flyteplugins/pull/404
- https://github.com/flyteorg/flyte/pull/4034

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Future-Outlier** [comment]
Hi, just noticed that AWS Athena wasn't listed.
Can I implement it?
